### ISSUE TITLE
Difference between resize results between System.Drawing & Imagesharp

### ISSUE THREAD

**Issue by wcrooy** [JimBobSquarePants/ImageSharp#82]
Hi I'm using this file as the input:

![orgtest](https://cloud.githubusercontent.com/assets/8612260/22060234/4624898a-dd70-11e6-9648-71012cfaa8fa.jpg)

You probably allready are aware of that but with System.Drawing it takes on avg: 300ms and with ImageSharp arround 1300ms. Anyway to speed it up?

I also noticed a considerable difference in the resized image.
Done with System.Drawing with these settings:
```cs
                        graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                        graphics.CompositingQuality = CompositingQuality.HighQuality;
                        graphics.SmoothingMode = SmoothingMode.HighQuality;
                        graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;
```
This is the result from System.Drawing:
![currently](https://cloud.githubusercontent.com/assets/8612260/22060488/41ce58ba-dd71-11e6-9e63-7eed997871b7.jpg)

With ImageSharp
```cs
var im = new Image(stream);
im.Resize(1300, 866, new BicubicResampler()).Save(targetStream);
```
It looks like the ImageSharp Resized image contains a bit more green. And the filesize is 64kb bigger then the System.Drawing example. I get comparable results with other samplers. 
![2017-1-18113134](https://cloud.githubusercontent.com/assets/8612260/22060621/d34a0fc8-dd71-11e6-8031-98a030f2e99d.jpg)

Am I doing something wrong. Is this as designed?

PS: ImageMagick (Magick.Net or Node.JS) and OpenCV return a result very similar to System.Drawing.

**Comment by JimBobSquarePants** [comment]
>You probably allready are aware of that but with System.Drawing it takes on avg: 300ms and with ImageSharp arround 1300ms. Anyway to speed it up?

Well I guess I could start a multinational tech giant, throw millions of dollars and thousands of man hours at it...

Seriously, this is **alpha** software developed by a very small team of dedicated individuals trying to do some good in the world. The only way we can make our jpeg codecs faster and produce more optimized output is with help, of which we get very little. 

>It looks like the ImageSharp Resized image contains a bit more green.

Well... They'll be using different samplers won't they? HighQualityBicubic isn't really Bicubic, if it was then the output would be the same. Personally if you want high quality output I would recommend the Lanczos3 resampler (for enlarging probably MitchellNetravali).

**Comment by wcrooy** [comment]
Hi @JimBobSquarePants I saw your rant on twitter. I'm sorry to bother you. But I actually try to help. 
Being rude IMHO doesn't make ppl to contribute. But please don't try to rant straightaway with I think is some sort of a normal question. 
Perhaps I can help optimize the code myself as well. But some pointers could make life a bit more easy.
And to discover. Why there's a difference between resizing an image. The funny thing, if I use default settings with OpenCV (bicubic) or ImageMagick, I get almost the same result as with System.Drawing.

**Comment by davepermen** [comment]
well, system.drawing uses raw c most likely, maybe even hw acceleration from gpu. it should be unbeatable in perf except going all that way, too (which, imho, shouldn't be done).

the interpolators are indeed different, that affects the image.

the one point i wonder about is the more "greenness".

oh, and a round of hugs for @JimBobSquarePants he does great work. i can understand it being very tiring at some point.. :(

**Comment by jackmott** [comment]
Looking at the resize code just briefly, some things I would try, along with benchmarking to confirm it is worth it

* replace Parallel.For with your own hand coded Threads. This is not super hard for this kind of code. Get core count, make ~corecount threads, split array up evenly among them, wait till they are all done. Parallel.For is super handy but there is a ton of overhead.

* use unsafe code to get array bounds elision as you iterate over pixels. Because you will be splitting the work up over different regions of the array, the .NET JIT will not elide array bounds checks. With unsafe code you can get around that.

* consider System.Numerics SIMD path for systems that can use it.

**Comment by jackmott** [comment]
I get a similar benchmark result to the OP only if I use a debug build of ImageSharp.
With a release build, ImageSharp is faster:

``` ini

BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6700 CPU 3.40GHz, ProcessorCount=8
Frequency=3328128 Hz, Resolution=300.4692 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0 [AttachedDebugger]
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0


```
                  Method |       Mean |    StdDev | Scaled | Scaled-StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
------------------------ |----------- |---------- |------- |-------------- |--------- |--------- |--------- |---------- |
 'System.Drawing Resize' | 51.8608 ms | 0.0884 ms |   1.00 |          0.00 |        - |        - |        - |     512 B |
     'ImageSharp Resize' | 33.5187 ms | 0.2249 ms |   0.65 |          0.00 | 345.8333 | 345.8333 | 345.8333 |  20.08 MB |

**Comment by JimBobSquarePants** [comment]
@wcrooy There really was no intent on being rude so I'll apologise here as well as Twitter.

@davepermen The greenness might have been caused by a lower level of accuracy translating RGBA to YCrCr in the jpeg encoder (and the reverse in the decoder) I pushed a change last night that to my eye improved things and a per-pixel comparison in Beyond Compare indicated that the rgb values were less green. If someone else could confirm that it would be great.

@jackmott That benchmark is just for resize though yeah? The issues we have are mostly in the jpeg decoder. One of our team @antonfirsov has done some extraordinary work speeding it up so far (10x faster than BitMiracle.LibJpeg.NET, using over 170MB less memory in my recent testing) but it's still ~4-5 slower than System.Drawing.

**Comment by jackmott** [comment]
@JimBobSquarePants ahh, I See. I'll take a look at that.

**Comment by antonfirsov** [comment]
@jackmott  @wcrooy or anyone who is interested in the speed of jpeg decoder/decoder:

For me the next step would be to figure out whether System.Drawing achieves it's performance by utilizing multiple cores. If the answer is yes, then it's possible to win this "fight" :)

It would be nice to have an optional switch on [our](https://github.com/JimBobSquarePants/ImageSharp/blob/master/tests/ImageSharp.Benchmarks/Image/DecodeJpegMultiple.cs) [benchmarks](https://github.com/JimBobSquarePants/ImageSharp/blob/master/tests/ImageSharp.Benchmarks/Image/EncodeJpegMultiple.cs), so we can run them with single thread affinity, and compare the results.

**Comment by antonfirsov** [comment]
There is `JobExtensions.WithAffinity()`, but haven't played with it yet. 

We need to find a way to (at least roughly) measure [speedup ratios](http://www.bu.edu/tech/support/research/training-consulting/online-tutorials/matlab-pct/scalability/) of different solutions.

**Comment by wcrooy** [comment]
Thanks for the help so far. 
@JimBobSquarePants I checked the latest code. 
```
"ImageSharp": "1.0.0-alpha1-00049",
"ImageSharp.Processing": "1.0.0-alpha1-00034",
"ImageSharp.Formats.Jpeg": "1.0.0-alpha1-00029",
"ImageSharp.Drawing": "1.0.0-alpha1-00029"
```

But I'm still getting a certain amount of extra _green_ in the resized picture. Regardless of the resampler I'm using.

**Comment by JimBobSquarePants** [comment]
Hmmmm... I can't explain that then. Our color translation should be very accurate.

**Comment by JimBobSquarePants** [comment]
Oh, those versions aren't the latest btw. You're at least 5 builds behind.

**Comment by wcrooy** [comment]
Sorry my bad. I just upgraded to the latest versions. It for some pictures less. (For example night-shots). But for the above picture it stays the same for some reason.

**Comment by JimBobSquarePants** [comment]
@wcrooy Here's the latest comparisons. There's certainly less green in the later version than before now that the conversion accuracy has been improved. Still more than System.Drawing though.

As far as I can see the algorithms I'm using are correct. The resamplers have been tested using ImageWorsener to ensure accuracy and the color transform output matches other libraries passing equivalent unit tests. I'd like to see the output from those other libraries you tested against if I could to do a full spectrum compare.

**System.Drawing**
![System Drawing](https://cloud.githubusercontent.com/assets/385879/22674198/c72d1d18-ed32-11e6-8f5d-b3923e2d6947.jpg)

**ImageSharp Old**
![ImageSharp Old](https://cloud.githubusercontent.com/assets/385879/22674248/024effce-ed33-11e6-874b-bf7afd52cf4d.jpg)

**ImageSharp Latest**
![ImageSharp Latest](https://cloud.githubusercontent.com/assets/385879/22674173/9bcb6c06-ed32-11e6-974f-b1adf3f2e3d9.jpg)

**Comment by JimBobSquarePants** [comment]
@wcrooy Good news! 

I finally got around to switching out our color conversion methods with ones mathematically identical to those used by libjpeg and libjpeg turbo. If you check out the PR mentioned above you'll see a quite dramatic difference.

Thanks for your patience 👍

**Comment by wcrooy** [comment]
@JimBobSquarePants Awesome. Thanks. I'll have a go asap. Curious to see this improvement.
